services:
  - type: web
    name: realtime-agents-app
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: realtime-agents-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false

databases:
  - name: realtime-agents-db
    databaseName: realtime_agents
    user: postgres
    plan: starter